# Configuración alternativa de Nixpacks - Sin Composer
# Renombra este archivo a nixpacks.toml si tienes problemas con Composer

[variables]
    PHP_VERSION = "8.1"

[phases.setup]
nixPkgs = [
    "php81",
    "php81Extensions.mysqli", 
    "php81Extensions.pdo",
    "php81Extensions.pdo_mysql",
    "php81Extensions.gd",
    "php81Extensions.zip",
    "php81Extensions.mbstring"
]

[phases.build]
cmds = [
    "echo 'Build sin Composer - usando librerías incluidas'",
    "chmod -R 755 .",
    "find . -type d -exec chmod 755 {} \\;",
    "find . -type f -exec chmod 644 {} \\;"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t . index.php"