# Nixpacks Configuration for Railway
[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.setup]
nixPkgs = ["php81", "php81Extensions.mysqli", "php81Extensions.pdo", "php81Extensions.pdo_mysql", "php81Extensions.gd", "php81Extensions.zip", "php81Extensions.mbstring"]

[start]
cmd = "php -S 0.0.0.0:$PORT"