# Nixpacks Configuration for Railway - PHP Project
[variables]
    PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.mysqli", 
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.gd",
    "php82Extensions.zip",
    "php82Extensions.mbstring",
    "php82Packages.composer"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-interaction",
    "chmod -R 755 .",
    "find . -type d -exec chmod 755 {} \\;",
    "find . -type f -exec chmod 644 {} \\;"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t . index.php"